import { IndicatorKey, VerifiedParameters } from '../../types/crypto.types';

export interface ParameterFieldMeta {
  key: string;
  label: string;
  description: string;
  defaultValue: number;
  min: number;
  max: number;
  step: number;
  unit?: string;
}

export interface IndicatorMeta {
  key: IndicatorKey;
  name: string;
  shortName: string;
  origin: string;
  verificationSource: string;
  description: string;
  parameters: ParameterFieldMeta[];
}

export const DEFAULT_VERIFIED_PARAMETERS: VerifiedParameters = {
  priceAction: {
    swingLookback: 20,
    pinBarRatio: 2.0,
  },
  vwap: {
    band1StdDev: 1.0,
    band2StdDev: 2.0,
  },
  rsi: {
    period: 14,
    overbought: 70,
    oversold: 30,
    divergenceLookback: 10,
  },
  ichimoku: {
    tenkan: 9,
    kijun: 26,
    senkouB: 52,
  },
  fibonacci: {
    swingLookback: 30,
    goldenPocketMin: 0.618,
    goldenPocketMax: 0.650,
  },
  macd: {
    fastPeriod: 12,
    slowPeriod: 26,
    signalPeriod: 9,
  },
  smc: {
    orderBlockLookback: 20,
    minFvgGapPct: 0.15,
  },
  ict: {
    oteMin: 0.62,
    oteMax: 0.79,
    discountThreshold: 0.5,
  },
  elliottWave: {
    wave3MinExtension: 1.618,
    trendLookback: 30,
  },
  tdSequential: {
    setupLength: 9,
  },
  orderFlow: {
    cvdLookback: 20,
    deltaThresholdRatio: 1.25,
  },
  optionFlow: {
    pcrBullishThreshold: 0.75,
    pcrBearishThreshold: 1.15,
  },
  confluence: {
    minScoreThreshold: 60,
    minAgreedIndicators: 7,
    strategyMode: 'weighted',
  },
};

export const INDICATORS_CATALOG: IndicatorMeta[] = [
  {
    key: 'confluence',
    name: 'Konsensus 12 Indikator (Confluence Engine)',
    shortName: '12-Confluence',
    origin: 'IMASBTC Quant Multi-Model Consensus',
    verificationSource: 'Institutional Weighted Voting Model (Score >= 60/100)',
    description: 'Menggabungkan sinyal dari seluruh 12 indikator kuantitatif dengan bobot institusional terkalibrasi untuk memfilter false signal.',
    parameters: [
      {
        key: 'minScoreThreshold',
        label: 'Skor Ambang Minimal',
        description: 'Skor konfluensi minimum untuk memicu eksekusi beli/jual (0-100)',
        defaultValue: 60,
        min: 50,
        max: 85,
        step: 5,
        unit: 'pts',
      },
      {
        key: 'minAgreedIndicators',
        label: 'Konsensus Minimal Indikator',
        description: 'Jumlah minimum indikator dari 12 model yang harus searah (bullish/bearish)',
        defaultValue: 7,
        min: 4,
        max: 11,
        step: 1,
        unit: 'ind',
      },
    ],
  },
  {
    key: 'rsi',
    name: 'Relative Strength Index (RSI)',
    shortName: 'RSI (14)',
    origin: 'J. Welles Wilder Jr. (1978)',
    verificationSource: 'Standar Industri 14 Periode & Wilder Smoothing',
    description: 'Mengukur kecepatan dan perubahan pergerakan harga dengan zona jenuh beli dan jenuh jual terverifikasi.',
    parameters: [
      {
        key: 'period',
        label: 'Periode RSI',
        description: 'Jumlah lilin historis untuk penghitungan momentum (Standar Wilder: 14)',
        defaultValue: 14,
        min: 5,
        max: 30,
        step: 1,
        unit: 'bars',
      },
      {
        key: 'overbought',
        label: 'Batas Overbought',
        description: 'Ambang jenuh beli di mana harga rentan mengalami koreksi (Standar: 70)',
        defaultValue: 70,
        min: 65,
        max: 85,
        step: 1,
        unit: 'pts',
      },
      {
        key: 'oversold',
        label: 'Batas Oversold',
        description: 'Ambang jenuh jual di mana harga berpotensi rebound (Standar: 30)',
        defaultValue: 30,
        min: 15,
        max: 35,
        step: 1,
        unit: 'pts',
      },
    ],
  },
  {
    key: 'macd',
    name: 'MACD (Moving Average Convergence Divergence)',
    shortName: 'MACD (12, 26, 9)',
    origin: 'Gerald Appel (1979)',
    verificationSource: 'Standar Standalone 12/26/9 Exponential Moving Average',
    description: 'Indikator momentum pengikut tren yang menunjukkan hubungan antara dua rata-rata pergerakan harga.',
    parameters: [
      {
        key: 'fastPeriod',
        label: 'Periode Cepat (Fast EMA)',
        description: 'Panjang EMA jangka pendek untuk mengukur pergerakan terkini (Standar: 12)',
        defaultValue: 12,
        min: 5,
        max: 20,
        step: 1,
        unit: 'bars',
      },
      {
        key: 'slowPeriod',
        label: 'Periode Lambat (Slow EMA)',
        description: 'Panjang EMA jangka menengah untuk dasar tren (Standar: 26)',
        defaultValue: 26,
        min: 18,
        max: 40,
        step: 1,
        unit: 'bars',
      },
      {
        key: 'signalPeriod',
        label: 'Garis Sinyal (Signal EMA)',
        description: 'Rata-rata EMA garis MACD untuk deteksi persilangan (Standar: 9)',
        defaultValue: 9,
        min: 4,
        max: 15,
        step: 1,
        unit: 'bars',
      },
    ],
  },
  {
    key: 'ichimoku',
    name: 'Ichimoku Kinko Hyo (Awan Kumo)',
    shortName: 'Ichimoku (9, 26, 52)',
    origin: 'Goichi Hosoda (1969)',
    verificationSource: 'Parameter Klasik Hosoda: Tenkan 9, Kijun 26, Senkou B 52',
    description: 'Sistem grafik ekuilibrium komprehensif penentu arah tren, momentum, dan level support/resistance dinamis.',
    parameters: [
      {
        key: 'tenkan',
        label: 'Tenkan-sen (Conversion)',
        description: 'Rata-rata titik tengah jangka pendek (Standar Hosoda: 9)',
        defaultValue: 9,
        min: 5,
        max: 15,
        step: 1,
        unit: 'bars',
      },
      {
        key: 'kijun',
        label: 'Kijun-sen (Base Line)',
        description: 'Rata-rata titik tengah jangka menengah sebagai konfirmasi tren (Standar Hosoda: 26)',
        defaultValue: 26,
        min: 15,
        max: 35,
        step: 1,
        unit: 'bars',
      },
      {
        key: 'senkouB',
        label: 'Senkou Span B (Leading)',
        description: 'Titik tengah jangka panjang pembuat awan Kumo terkuat (Standar Hosoda: 52)',
        defaultValue: 52,
        min: 40,
        max: 65,
        step: 1,
        unit: 'bars',
      },
    ],
  },
  {
    key: 'priceAction',
    name: 'Price Action & Candlestick Structuring',
    shortName: 'Price Action',
    origin: 'Nial Fuller / Steve Nison Candlestick Science',
    verificationSource: 'Pola Pin Bar (Wick 2.0x) & Engulfing Reversal',
    description: 'Analisis murni aksi harga tanpa lag melalui formasi candlestick dan rejeksi area support/resistance.',
    parameters: [
      {
        key: 'swingLookback',
        label: 'Jangkauan Swing High/Low',
        description: 'Jumlah lilin untuk mengidentifikasi level struktural harga tertinggi/terendah',
        defaultValue: 20,
        min: 10,
        max: 40,
        step: 2,
        unit: 'bars',
      },
      {
        key: 'pinBarRatio',
        label: 'Rasio Sumbu Pin Bar',
        description: 'Kelipatan panjang ekor lilin terhadap ukuran badan lilin (Standar: 2.0x)',
        defaultValue: 2.0,
        min: 1.5,
        max: 3.5,
        step: 0.1,
        unit: 'x',
      },
    ],
  },
  {
    key: 'vwap',
    name: 'VWAP & Standar Deviasi Bands',
    shortName: 'VWAP Bands',
    origin: 'Institusi Eksekusi Perdagangan Saham/Futures (Berwin 1988)',
    verificationSource: 'Standar Deviasi 1.0σ & 2.0σ Weighted by Volume',
    description: 'Harga rata-rata tertimbang volume yang digunakan institusi besar sebagai patokan nilai wajar intraday.',
    parameters: [
      {
        key: 'band1StdDev',
        label: 'Pita Deviasi 1 (1.0σ)',
        description: 'Kelipatan standar deviasi pertama untuk pullback wajar',
        defaultValue: 1.0,
        min: 0.5,
        max: 1.5,
        step: 0.1,
        unit: 'σ',
      },
      {
        key: 'band2StdDev',
        label: 'Pita Deviasi 2 (2.0σ)',
        description: 'Kelipatan deviasi kedua penanda kondisi overextended institusional',
        defaultValue: 2.0,
        min: 1.8,
        max: 3.0,
        step: 0.1,
        unit: 'σ',
      },
    ],
  },
  {
    key: 'fibonacci',
    name: 'Fibonacci Retracement & Golden Pocket',
    shortName: 'Fibonacci (0.618)',
    origin: 'Leonardo Fibonacci / Pasar Keuangan Modern',
    verificationSource: 'Golden Pocket Ratio 0.618 - 0.650',
    description: 'Menemukan area retracement kritis dengan rasio emas matematika 0.618 dan target ekspansi 1.618.',
    parameters: [
      {
        key: 'swingLookback',
        label: 'Lookback Swing Fib',
        description: 'Jumlah lilin acuan untuk menentukan swing high dan low utama',
        defaultValue: 30,
        min: 15,
        max: 60,
        step: 5,
        unit: 'bars',
      },
      {
        key: 'goldenPocketMin',
        label: 'Batas Bawah Golden Pocket',
        description: 'Level rasio emas bawah (Standar: 0.618)',
        defaultValue: 0.618,
        min: 0.5,
        max: 0.64,
        step: 0.01,
        unit: 'ratio',
      },
      {
        key: 'goldenPocketMax',
        label: 'Batas Atas Golden Pocket',
        description: 'Level rasio emas atas (Standar: 0.650)',
        defaultValue: 0.65,
        min: 0.64,
        max: 0.72,
        step: 0.01,
        unit: 'ratio',
      },
    ],
  },
  {
    key: 'smc',
    name: 'Smart Money Concepts (SMC)',
    shortName: 'SMC (OB & FVG)',
    origin: 'Institusional Liquidity Order Flow Trading',
    verificationSource: 'Mitigated Order Blocks & Fair Value Gap >= 0.15%',
    description: 'Melacak jejak dana institusi pintar melalui blok order (OB) dan ketidakseimbangan harga (FVG).',
    parameters: [
      {
        key: 'orderBlockLookback',
        label: 'Lookback Order Block',
        description: 'Rentang lilin historis pencarian blok order unmitigated',
        defaultValue: 20,
        min: 10,
        max: 40,
        step: 2,
        unit: 'bars',
      },
      {
        key: 'minFvgGapPct',
        label: 'Minimal Gap FVG (%)',
        description: 'Ukuran celah 3-lilin minimal yang valid sebagai Fair Value Gap (Standar: 0.15%)',
        defaultValue: 0.15,
        min: 0.05,
        max: 0.5,
        step: 0.05,
        unit: '%',
      },
    ],
  },
  {
    key: 'ict',
    name: 'Inner Circle Trader (ICT OTE)',
    shortName: 'ICT OTE',
    origin: 'Michael J. Huddleston (ICT)',
    verificationSource: 'Optimal Trade Entry 0.62 - 0.79 Fib Range',
    description: 'Strategi likuiditas terarah berbasis zona diskon/premium dan zona masuk optimal (OTE).',
    parameters: [
      {
        key: 'oteMin',
        label: 'Ambang Minimal OTE',
        description: 'Batas bawah zona Optimal Trade Entry (Standar: 0.62)',
        defaultValue: 0.62,
        min: 0.55,
        max: 0.68,
        step: 0.01,
        unit: 'ratio',
      },
      {
        key: 'oteMax',
        label: 'Ambang Maksimal OTE',
        description: 'Batas atas zona Optimal Trade Entry (Standar: 0.79)',
        defaultValue: 0.79,
        min: 0.72,
        max: 0.85,
        step: 0.01,
        unit: 'ratio',
      },
    ],
  },
  {
    key: 'elliottWave',
    name: 'Elliott Wave Theory',
    shortName: 'Elliott Wave',
    origin: 'Ralph Nelson Elliott (1938)',
    verificationSource: 'Ekspansi Motive Gelombang 3 >= 1.618x Gelombang 1',
    description: 'Mengidentifikasi siklus psikologi pasar fraktal 5-gelombang impuls dan 3-gelombang korektif.',
    parameters: [
      {
        key: 'wave3MinExtension',
        label: 'Ekspansi Minimal Gelombang 3',
        description: 'Rasio kelipatan panjang Gelombang 3 dibanding Gelombang 1 (Standar: 1.618)',
        defaultValue: 1.618,
        min: 1.382,
        max: 2.618,
        step: 0.05,
        unit: 'x',
      },
      {
        key: 'trendLookback',
        label: 'Lookback Siklus Tren',
        description: 'Jumlah lilin untuk penentuan titik awal perhitungan gelombang',
        defaultValue: 30,
        min: 15,
        max: 50,
        step: 5,
        unit: 'bars',
      },
    ],
  },
  {
    key: 'tdSequential',
    name: 'Tom DeMark TD Sequential (9-13 Countdown)',
    shortName: 'TD Sequential (9)',
    origin: 'Thomas DeMark (1994)',
    verificationSource: 'DeMark Setup 9 Bars Comparison vs Close[4]',
    description: 'Menemukan titik kelelahan tren ekstrem (Setup 9) untuk memprediksi pembalikan arah harga.',
    parameters: [
      {
        key: 'setupLength',
        label: 'Panjang Setup DeMark',
        description: 'Jumlah lilin berurutan yang harus menutup di atas/bawah 4 lilin sebelumnya (Standar: 9)',
        defaultValue: 9,
        min: 6,
        max: 13,
        step: 1,
        unit: 'bars',
      },
    ],
  },
  {
    key: 'orderFlow',
    name: 'Order Flow (Cumulative Volume Delta & Aggression)',
    shortName: 'Order Flow (CVD)',
    origin: 'CME Market Profile & Volume Delta Analysis',
    verificationSource: 'Cumulative Aggressive Taker Volume Delta (Delta Ratio >= 1.25)',
    description: 'Menganalisis akumulasi dan distribusi riil pembeli vs penjual pasar agresif (taker) serta zona absorpsi likuiditas.',
    parameters: [
      {
        key: 'cvdLookback',
        label: 'Lookback Batang CVD',
        description: 'Jumlah lilin untuk menghitung trajektori delta volume kumulatif',
        defaultValue: 20,
        min: 10,
        max: 50,
        step: 5,
        unit: 'bars',
      },
      {
        key: 'deltaThresholdRatio',
        label: 'Ambang Rasio Delta',
        description: 'Rasio minimum volume beli agresif terhadap jual agresif untuk konfirmasi tren',
        defaultValue: 1.25,
        min: 1.10,
        max: 2.00,
        step: 0.05,
        unit: 'x',
      },
    ],
  },
  {
    key: 'optionFlow',
    name: 'Option Flow (Put/Call Ratio & Max Pain)',
    shortName: 'Option Flow',
    origin: 'Deribit / Institutional Crypto Derivatives Options Desk',
    verificationSource: 'Put/Call Open Interest Ratio & Max Pain Magnetic Pinning',
    description: 'Memantau sentimen institusi melalui rasio Put/Call derivatif, titik gravitasi Max Pain, dan eksposur Gamma (GEX).',
    parameters: [
      {
        key: 'pcrBullishThreshold',
        label: 'Batas Bawah PCR (Bullish Call Heavy)',
        description: 'Ambang rasio Put/Call di mana akumulasi Call mendominasi pasar opsi',
        defaultValue: 0.75,
        min: 0.50,
        max: 0.90,
        step: 0.05,
        unit: 'ratio',
      },
      {
        key: 'pcrBearishThreshold',
        label: 'Batas Atas PCR (Bearish Put Heavy)',
        description: 'Ambang rasio Put/Call di mana lindung nilai (Put hedging) mendominasi',
        defaultValue: 1.15,
        min: 1.00,
        max: 1.50,
        step: 0.05,
        unit: 'ratio',
      },
    ],
  },
];
